import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "@components/common/navbar";
import Footer from "@components/common/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Web3Provider from "@components/provider/web3";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased pt-16`}
      >
        <Web3Provider>
          <div className="  overflow-hidden">
            <div className="relative max-w-7xl mx-auto px-4">
              {/*------ NAVBAR STARTS ------*/}
              <Navbar></Navbar>
              {/*------ NAVBAR ENDS ------*/}
              <div className="fit">{children}</div>
            </div>
            {/*------ FOOTER STARTS ------*/}
            <Footer></Footer>
            {/*------ FOOTER ENDS ------*/}
          </div>
        </Web3Provider>
      </body>
    </html>
  );
}
